# Site settings
site: EMO醬的小天地
title: EMO醬的小天地
keywords: blog
description: >-
  EMO醬的文章喵！
lang: zh-TW
timezone:  Asia/Hong_Kong
repo: 1f616neko/blog # site repo [optional]
repository: 1f616neko/blog

# Author settings
author:
  name: 可愛EMO醬！
  bio: 是可愛喵男！<br />
  picture: https://upload.wikimedia.org/wikipedia/commons/7/7c/Twemoji12_1f616.svg
  github: Emojigit # github username
  twitter: "1F616EMO" # twitter username
  facebook: # facebook username
  instagram: # instagram username
  youtube: # youtube username
  linkedin: # linkedin username
  email: emonya@duck.com # email adress
  telegram: "@emojiwiki" # Telegram username


# URL settings
url: "https://blog.1f616emo.xyz" # Domain Name of host. [username].github.io for github pages
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE_OF_THEME.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comment: true

relative_links:
  enabled:     true
  collections: false


